apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ include "puller.name" . }}
  name: {{ include "puller.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "puller.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "puller.name" . }}
    namespace:  {{ .Release.Namespace }}